Initial import of task-09 (basic RPL)
RIOT-OS/Tutorials pull request #18
Opened 2016-10-19 10:06 UTC by PeterKietzmann

2016-10-19 10:15 UTC, cgundogan commented on task-09/README.md
> +This task will demonstrate basic routing functionalities in RIOT provided by the RPL (IPv6 Routing Protocol for Low-Power and Lossy Networks) routing protocol and multihop communication.
please reference https://tools.ietf.org/html/rfc6550 when talking about [RPL](https://tools.ietf.org/html/rfc6550)

2016-10-20 14:21 UTC, PeterKietzmann commented
@cgundogan please check out the latest commits!

2016-10-20 14:46 UTC, cgundogan requested changes

2016-10-20 14:46 UTC, cgundogan commented on task-09/README.md
> +ifconfig 7 set chan 11
Please be more generic (use `<if_id>` instead of `7`). `7` could change in the future

2016-10-20 14:46 UTC, cgundogan commented on task-09/README.md
> +(Please note that the network interface is `6` when running on native)
use a more generic `<if_id>`. here and all following

2016-10-20 14:46 UTC, cgundogan commented on task-09/README.md
> +* Build groups of at least three persons
maybe be more generic? instead of "group of persons" just "gather 3 boards"?

2016-10-20 14:46 UTC, cgundogan commented on task-09/README.md
> +* Typing `rpl` gives you some information about the nodes position in the DODAG. Check the local IPv6 address of the selected parent node. Look for value `R:` which describes the "rank" or more gener
Look for value `R:` which describes the "rank" or more general, ~~the hop count metric.~~ the position in the DODAG according to the metric.

2016-10-20 14:46 UTC, cgundogan commented on task-09/main.c
> +            ipv6_hdr_t *ipv6_hdr = pkt->next->data;
using `LL_SEARCH` to search for the ipv6 packet may be more appropriate, in case there is something in between?

2016-10-20 14:46 UTC, cgundogan commented on task-09/main.c
> +                            ipv6_addr_to_str(addr_str, &(ipv6_hdr->src), sizeof(addr_str)),
btw: you can use the same `addr_str` buffer for `ipv6_addr_to_str` if you split this into two `printf` calls

2016-10-20 14:46 UTC, cgundogan commented on task-09/task-09.patch
> +From f806bf796c60ded00c0abb4521c9bc3955efd63f Mon Sep 17 00:00:00 2001
remove this patch

2016-10-20 15:41 UTC, cgundogan commented on task-09/README.md
> +rpl init <if_id>
you don't need this when including in your makefile: `USEMODULE += auto_init_gnrc_rpl`

2016-10-20 15:50 UTC, cgundogan commented
ACK & GO

2016-10-20 15:50 UTC, merged