Small fixes
RIOT-OS/Tutorials pull request #36
Opened 2017-11-22 22:51 UTC by OlegHahm

The current pandoc version (2.0.1.1) requires some changes.

2017-11-23 08:39 UTC, miri64 requested changes

2017-11-23 08:39 UTC, miri64 commented on slides/slides.md
> +\only<2>{\includegraphics[width=\textwidth]{pictures/overview-net-sock.pdf}}
Unrelated?

2017-11-23 08:39 UTC, miri64 commented on slides/slides.md
> +* Compile, flash, and run on the board `BOARD=iotlab-m3 make iotlab-flash iotlab-term`
Unrelated?

2017-11-24 09:24 UTC, OlegHahm commented on slides/slides.md
> +* Compile, flash, and run on the board `BOARD=iotlab-m3 make iotlab-flash iotlab-term`
oops, will fix

2017-11-24 09:24 UTC, OlegHahm commented on slides/slides.md
> +\only<2>{\includegraphics[width=\textwidth]{pictures/overview-net-sock.pdf}}
yupp

2023-11-30 13:08 UTC, miri64 commented
Ping @OlegHahm?

2023-12-02 20:53 UTC, OlegHahm commented
Pong - took me only six years...

2025-03-11 18:01 UTC, OlegHahm commented
@miri64 could you take another look?

2025-03-11 18:03 UTC, miri64 approved these changes

2025-03-12 17:48 UTC, merged