Update Task-07 to work with current RIOT-OS API
RIOT-OS/Tutorials pull request #45
Opened 2018-08-01 13:38 UTC by Quintol

Added msg_init_queue to Task 7.2.
Changed server creation to use macro.

2018-08-01 14:40 UTC, PeterKietzmann requested changes
@Quintol thanks a lot for your contribution!

2018-08-01 14:40 UTC, PeterKietzmann commented on task-07/README.md
>  * Add the `gnrc_udp` module to the application's [Makefile](Makefile)
While you're at it, could you adapt the link to the Makefile as well?

2018-08-01 14:40 UTC, PeterKietzmann commented on task-07/README.md
> +* To be able to receive packets, a packet buffer must be created using [msg_init_queue](https://doc.riot-os.org/group__core__msg.html#ga480e6f32c8ab18579b62a890f3fda2cd):
That is not entirely correct. The `netreg ` (which is mentioned below) requires a queue in the default case (check description for [`gnrc_netreg_register()`](https://doc.riot-os.org/group__net__gnrc__netreg.html). This is also stated [here](https://doc.riot-os.org/group__net__gnrc.html) under "Architecture" point 1. The packet buffer has nothing to to with that. Please rephrase and reference one of the sources I linked (if you think it makes sense). Now that this is a requirement of `netreg`, wouldn't it make sense to explain it after the function is mentioned the first time (see some lines below)?

2018-08-01 14:40 UTC, PeterKietzmann commented on task-07/README.md
> +* To be able to receive packets, a packet buffer must be created using [msg_init_queue](https://doc.riot-os.org/group__core__msg.html#ga480e6f32c8ab18579b62a890f3fda2cd):
Furthermore, please reduce the line width to something around 80-90.

2018-08-17 09:19 UTC, PeterKietzmann commented
@Quintol ping

2018-08-17 10:33 UTC, Quintol commented
Forgot to commit my local changes... should be all there now

2018-08-17 11:13 UTC, PeterKietzmann commented on task-07/README.md
> +* Add the `gnrc_udp` module to the application's [Makefile](https://github.com/RIOT-OS/RIOT/blob/master/examples/gnrc_minimal/Makefile)
@Quintol thanks for addressing the other comments. Would you please split this line, for example before the Makefile reference? We should be ready to go afterwards

2018-08-17 11:19 UTC, PeterKietzmann commented
Nice! Please squash to one commits

2018-08-17 11:53 UTC, Quintol commented
If you can tell me how, i can to that

2018-08-17 12:04 UTC, PeterKietzmann commented
Have a look at [this](https://github.com/RIOT-OS/RIOT/wiki/Git-cheatsheet) and [this](https://davidwalsh.name/squash-commits-git) guide or any other online tutorial for detailed instructions. Now that you did your changes on your local master branch the procedure would look somehow like:

- `gir rebase -i HEAD~3`
- prefix the last 2 commits with an "`s`" for "squash" instead of "pick"
- save, exit, and you will get to the commit description. Comment the last two messages with an "`#`"
- save and exit
- check if it worked with `git log`
- force push your changes with `git push -f`

2018-08-17 12:41 UTC, Quintol commented
Done

2018-08-17 12:49 UTC, PeterKietzmann approved these changes
Thanks. ACK

2018-08-17 12:50 UTC, merged